### ISSUE TITLE
Fix ee-admin directory location to /var/www/htdocs

### ISSUE THREAD

**Issue by dhsathiya** [EasyEngine/admin-tools-command#45]
EE has `--public-dir=dir_name` option to change public dir to a custom location inside `/var/www/htdocs`, which is mainly helpful in CI/CD. 

When we enable admin-tools, a directory named `ee-admin` gets created inside public dir.
When new code gets deployed, `ee-admin` directory gets removed due to the deployment pipeline might not have `ee-admin` dir and due to which `ee-admin` stops working.

To fix this, we can create `ee-admin` directory in `/var/www/htocs/` instead of public dir.

---

**Solution**
File name: `docker-compose-admin.yml`
```yml
version: '3.5'

services:

  php:
    environment:
      - REDIS_HOST=
      - DB_HOST=global-db
    volumes:
      - "/opt/easyengine/admin-tools:/var/www/htdocs/ee-admin:ro"
      - "/opt/easyengine/db/ee.sqlite:/opt/easyengine/db/ee.sqlite:ro"

  nginx:
    volumes:
      - "/opt/easyengine/admin-tools:/var/www/htdocs/ee-admin:ro"
      - "/opt/easyengine/db/ee.sqlite:/opt/easyengine/db/ee.sqlite:ro"
```
File name: `nginx/conf.d/main.conf`
```nginx
location ^~ /ee-admin/ {
	root /var/www/htdocs ;
	location ~ \.php$ {
		try_files $uri =404;
		include fastcgi_params;
		fastcgi_pass php;
	}
}
```
